# Build releases and publish to PyPI if a tag is pushed
name: Release

on:
  pull_request:
  push:

jobs:
  build-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: install build requirements
        run: |
          pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip freeze

      - name: build release
        run: |
          # pep517 setuptools doesn't support editable installs
          # https://github.com/pypa/setuptools/issues/2816
          # so instead of pyproject.yml and `python -m build .` use setup.py:
          python setup.py sdist bdist_wheel
          ls -l dist

      # - name: publish to pypi
      #   uses: pypa/gh-action-pypi-publish@v1.4.1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     user: __token__
      #     password: ${{ secrets.pypi_password }}
