# Build releases and publish to PyPI if a tag is pushed
name: Release

on:
  pull_request:
  push:

jobs:
  build-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: install build package
        run: |
          pip install --upgrade pip
          pip install build
          pip freeze

      - name: build release
        run: |
          # Defaults to building sdist, and wheel from sdist
          python -m build .
          ls -l dist

      # - name: publish to pypi
      #   uses: pypa/gh-action-pypi-publish@v1.4.1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     user: __token__
      #     password: ${{ secrets.pypi_password }}
